### ISSUE TITLE
Disabling showLittleSticksPlug in settings.js doesn't work

### ISSUE THREAD

**Issue by KitAdams** [littlesticks/odyssey-theme#20]
I have set showLittleSticksPlug: false, in settings.js

Yet the Little Sticks plug in the footer remains active with the button **Get this template** still showing.

Am I missing something with removing this?

Thanks

**Comment by jaydanurwin** [comment]
Let me take a look @KitAdams, I recently changed some of the plug code so it could be an oversight from that.

**Comment by jaydanurwin** [comment]
@KitAdams I am not having any issues with on the latest code of the theme. If I set `showLittleSticksPlug` to `false` in the `settings.js` file it hides it from the footer for me?

**Comment by KitAdams** [comment]
@jaydanurwin - thanks for testing!

I am still seeing this:
![image](https://user-images.githubusercontent.com/47960871/197727476-bb7d135f-0ca2-4794-ade5-e2adedfc78dc.png)

![image](https://user-images.githubusercontent.com/47960871/197727549-4d4e449d-452e-43a1-8453-f2fe26aba41a.png)

![image](https://user-images.githubusercontent.com/47960871/197727634-9ab38f04-4276-4a7a-810e-2b4d8a4395e7.png)

Let me retry cloning this and see if it occurs still.

**Comment by jaydanurwin** [comment]
@KitAdams Did you still have issues after re-cloning?

**Comment by KitAdams** [comment]
@jaydanurwin - all working after recloning this on my linux machine.

It may have been a Windows issue as this was where I first was using this.
