### ISSUE TITLE
Live demo website down

### ISSUE THREAD

**Issue by amserra** [littlesticks/odyssey-theme#38]
The live demo website is down: [live demo](https://odyssey-theme.littlesticks.site/)

**Comment by threelaina** [comment]
Just noticed that it appears down in Safari but does load in Firefox.

**Comment by lguima** [comment]
The domain has changed from:
- https://odyssey-theme.littlesticks.site/

to:
- https://odyssey-theme.littlesticks.dev/

---

Reference:
- https://astro.build/themes/details/odyssey/

**Comment by lguima** [comment]
I'd say the issue could be left open until the old references are updated.
