### ISSUE TITLE
Broken images in live demo and also README

### ISSUE THREAD

**Issue by SteveALee** [littlesticks/odyssey-theme#7]
https://odyssey-theme.littlesticks.dev/theme/get-started/

Firefox on Windows

![image](https://user-images.githubusercontent.com/618922/187635798-c5b59a4e-0318-4158-b5bb-73a938a0fb41.png)

![image](https://user-images.githubusercontent.com/618922/187636732-5db7ae5a-133e-4e80-8300-a7f342cc81df.png)

**Comment by jaydanurwin** [comment]
Thanks for filing this! It should now be fixed with #10 👍🏼
