### ISSUE TITLE
stakblitz missing images

### ISSUE THREAD

**Issue by SteveALee** [littlesticks/odyssey-theme#8]
I see it's running `astro dev` so maybe images need to be copied?

![image](https://user-images.githubusercontent.com/618922/187642734-7c8d1e68-a115-4f3e-9a0e-b8004b49c8e3.png)

**Comment by SteveALee** [comment]
It looks like a stakblitz issue with attaching to github https://github.com/stackblitz/webcontainer-core/issues/787

**Comment by jaydanurwin** [comment]
This may be fixed with #10? @SteveALee I just created a new Stackblitz to test and didn't have any errors on it starting up...
